import fs from "node:fs";
import path from "node:path";

import { generateSpeechMp3 } from "../services/elevenLabsClient";

/**
 * One-off script: (re)generate the INBOUND voice locuciones with the approved ElevenLabs
 * voices, so every leg of the inbound phone call sounds like the same person.
 *
 * The call is bilingual: the caller hears a short language menu, waits for Spanish or
 * presses 1 for English, and the rest of the call plays in the chosen language. Each
 * language has its own approved voice — Spanish lines are never spoken by the English
 * voice and vice versa, which is why the locución list carries a voiceId per entry.
 *
 * VOICE_ID_ES MUST match OUTBOUND_ELEVENLABS_VOICE_ID_DEFAULT in src/index.ts.
 *
 * IMPORTANT — most of these locuciones are `handMade` (see below) and a plain run SKIPS
 * them. Only the entries without that flag are regenerated by default. This is deliberate:
 * the approved recordings were tuned by ear in the ElevenLabs web UI with settings this
 * script does not reproduce, and re-rendering them would silently swap the audio callers
 * hear for a different take of the same words.
 *
 * Files are written to <repoRoot>/public/voice/ ; Vite copies public/ into dist/ on the
 * frontend build, and Firebase Hosting serves them under /voice/** with `Cache-Control: no-store`,
 * so overwriting in place is safe (no cache busting / filename versioning needed).
 *
 * Run:
 *   cd functions
 *   ELEVENLABS_KEY=<your-key> npm run generate:inbound-voice
 *   # or: npm run generate:inbound-voice -- --key=<your-key>
 *
 * Regenerating specific locuciones after a wording tweak (comma-separated, substring match):
 *   npm run generate:inbound-voice -- --key=<your-key> --only=message_part_2_optin_en
 */

// Approved ElevenLabs voices.
// Spanish — "Dani". Keep in sync with OUTBOUND_ELEVENLABS_VOICE_ID_DEFAULT in src/index.ts.
const VOICE_ID_ES = "7QQzpAyzlKTVrRzQJmTE";
// English (British) — "Daniel". Used only for the English branch of the inbound call.
const VOICE_ID_EN = "u8GDilEiJPUbRk87Lcqs";

type Locucion = {
  file: string;
  voiceId: string;
  /**
   * For generated entries: the exact text sent to ElevenLabs.
   * For `handMade` entries: a reference copy of the script, NOT the source of the audio —
   * the committed .mp3 is authoritative and may differ in wording or delivery.
   */
  text: string;
  /**
   * Recorded by hand in the ElevenLabs web UI and committed as-is. Skipped by a plain run.
   * Naming one explicitly with --only still regenerates it, which replaces the approved
   * take — only do that deliberately.
   */
  handMade?: true;
};

const LOCUCIONES: Locucion[] = [
  {
    // #1 — the language menu, and the first thing every caller hears. One bilingual file:
    // the Spanish voice reads the greeting, the "espere" instruction AND the English
    // "press 1" line, so the two halves can never drift apart.
    // Hand-made: professional voice clone, v3 model, speed 0.91 (file name records the settings).
    file: "message_part_1_menu.mp3",
    voiceId: VOICE_ID_ES,
    handMade: true,
    text: "Hola, gracias por llamar a nuestra agencia inmobiliaria. Para continuar en español, espere. To continue in English, press 1.",
  },
  {
    // #2 ES — opt-in prompt played inside the consent <Gather>.
    // Hand-made: the take that was already approved and live; kept deliberately.
    file: "message_part_2_optin.mp3",
    voiceId: VOICE_ID_ES,
    handMade: true,
    text: "Muchas gracias. Para ofrecerte un mejor servicio, actualmente agendamos visitas y resolvemos tus dudas por WhatsApp. Si quieres que te contactemos de inmediato, por favor pulse 1.",
  },
  {
    // #2 EN — same prompt for callers who chose English. The only script-generated locución
    // left, so a plain run regenerates exactly this one.
    file: "message_part_2_optin_en.mp3",
    voiceId: VOICE_ID_EN,
    text: "Thank you. To give you a better service, we currently arrange viewings and answer your questions on WhatsApp. If you would like us to contact you right away, please press 1.",
  },
  {
    // #3 ES — confirmation after the caller presses 1.
    // Hand-made: the take that was already approved and live; kept deliberately.
    file: "message_part_3.mp3",
    voiceId: VOICE_ID_ES,
    handMade: true,
    text: "Gracias. En breve recibirá un mensaje por WhatsApp.",
  },
  {
    // #3 EN — same confirmation for the English branch. Note it keeps the "Have a good day!"
    // sign-off that the Spanish side dropped along with "¡Un saludo!"; the two languages are
    // deliberately not word-for-word mirrors here.
    // Hand-made: professional voice clone, v3 model, speed 0.95. Text below transcribed from
    // the recording and confirmed by the author.
    file: "message_part_3_en.mp3",
    voiceId: VOICE_ID_EN,
    handMade: true,
    text: "Thank you. You will receive a WhatsApp message shortly. Have a good day!",
  },
];

function getArg(name: string): string | undefined {
  const prefix = `--${name}=`;
  const hit = process.argv.find((a) => a.startsWith(prefix));
  return hit ? hit.slice(prefix.length).trim() : undefined;
}

async function main(): Promise<void> {
  const apiKey = (getArg("key") || process.env.ELEVENLABS_KEY || process.env["11LABS_KEY"] || "").trim();
  if (!apiKey) {
    throw new Error('Missing ElevenLabs API key. Provide "--key=<key>" or set ELEVENLABS_KEY.');
  }

  // Optional filter so locuciones can be re-recorded one at a time after a wording tweak.
  // Comma-separated, matched as substrings. Worth using: ElevenLabs pins no seed, so
  // regenerating a locución whose text did NOT change still yields a different take of it.
  const only = (getArg("only") || "")
    .toLowerCase()
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  // Without --only, hand-made locuciones are left alone. Naming one explicitly overrides
  // that, so the protection can never become a wall — it just stops accidents.
  const targets = only.length
    ? LOCUCIONES.filter((l) => only.some((o) => l.file.toLowerCase().includes(o)))
    : LOCUCIONES.filter((l) => !l.handMade);

  if (!targets.length) {
    const names = LOCUCIONES.map((l) => `${l.file}${l.handMade ? " (hand-made)" : ""}`).join(", ");
    throw new Error(
      only.length ? `--only=${only.join(",")} matched none of: ${names}` : `Nothing to generate. Known locuciones: ${names}`
    );
  }

  const skipped = LOCUCIONES.filter((l) => !targets.includes(l));
  if (skipped.length) {
    console.log(`Skipping ${skipped.length} locución(es): ${skipped.map((l) => l.file).join(", ")}`);
  }

  // Compiled location: functions/lib/scripts/generateInboundVoice.js → repo root is three levels up.
  const repoRoot = path.resolve(__dirname, "..", "..", "..");
  const outDir = path.join(repoRoot, "public", "voice");
  fs.mkdirSync(outDir, { recursive: true });

  for (const loc of targets) {
    if (loc.handMade) {
      console.warn(`! ${loc.file} is hand-made — regenerating REPLACES the approved take.`);
    }
    process.stdout.write(`Generating ${loc.file} (voiceId ${loc.voiceId}) … `);
    const mp3 = await generateSpeechMp3({ apiKey, voiceId: loc.voiceId, text: loc.text });
    const dest = path.join(outDir, loc.file);
    fs.writeFileSync(dest, mp3);
    console.log(`done — ${mp3.length} bytes → ${dest}`);
  }

  console.log(`\n${targets.length} locución(es) generated with the approved ElevenLabs voices.`);
  console.log("Next: build the frontend and deploy hosting + the voice functions.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
